---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: ocp-1-vsphere-ocp
  namespace: vsphere-ocp
  labels:
    name: vsphere-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: LabDC
    cluster: LabCluster
    cluster-name: vsphere-ocp
    hostname: ocp-1
spec:
  config:
    dns-resolver:
      config:
        server:
          - 192.168.42.9
          - 192.168.42.10
        search:
          - kemo.labs
    interfaces:
      - ipv4:
          address:
            - ip: 192.168.42.78
              prefix-length: 24
          dhcp: False
          enabled: true
        name: ens192
        state: up
        type: ethernet
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.42.1
          next-hop-interface: ens192
          table-id: 254
  interfaces:
    - name: ens192
      macAddress: 00:51:56:42:07:92
