kind: Namespace
apiVersion: v1
metadata:
  name: tosin-ocp
  labels:
    name: tosin-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: Datacenter
    cluster: Cluster
    cluster-name: tosin-ocp
