---
apiVersion: v1
kind: Secret
metadata:
  name: loe-atl1-vcenter-credentials
  namespace: tosin-ocp
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "ztp-credentials/loe-atl1-vcenter-credentials"
  labels:
    name: tosin-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: Datacenter
    cluster: Cluster
    cluster-name: tosin-ocp
data: