---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: tosin-ocp
  namespace: tosin-ocp
  labels:
    name: tosin-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: Datacenter
    cluster: Cluster
    cluster-name: tosin-ocp
    agentclusterinstalls.extensions.hive.openshift.io/location: loe-atl1
    networkType: static
spec:
  agentLabels:
    agentclusterinstalls.extensions.hive.openshift.io/location: loe-atl1
  clusterRef:
    name: tosin-ocp
    namespace: tosin-ocp
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCi7sHUvK9PhsUFBg4eM5nNgEXmXCA4PWDrolFWL3REU2qBMDwhqSzSl4sQN0GPR6MNrYKB/5sdbDVIQCJlCkpszTCkpDQM+wtMSVSYSV3ZRWxGL0DybM+eIDkt4hVXRSmzwUz6sHXs8Mjc6T3WGzwc4ouIHvR1pJjZwn2gvLFJpIxnoN8XGgB7QSxwkak1o4NIMIclbODb8rQG220TjdpzcvEZFyAUMkEpWhMfGeoe2kBEjF9EKgGBA5jKSFZ7SC3rpDZQR+KWAqigNI6X+Depew6r+nBpJl3Ro0fjmJLjn2AcNI1c1kbBwayBFPBQKT49LiQWNwhopKKWGH/FStgKrNsYEQgWbnJmUfv3Tmt4EVFZvsz+i/CNQjHvzo6bzG+ZM/RxVB/kEQYFFYwCjlW3YbgkxQVcmMwjPxcF9qwrJz1Q7nanlVoFttDw7vw3UqNNN7MaSiqhmow+Q8FgyF2lmlziRINK0cj/ukN1QcuWvScfOEDZN6TDFvD42Rzo7OF8aCakmTmgOusgWEGbeD5CztHgkq6r3eyb3wIBMc9tYjvfd9MWOwLYaKHFw23lz90y92Bpsx3XAfUtjYRKUwRZ/9Mmdj0NEoDcpEUNVmKncSDhW4meewxaKoT2UV4nnRHL4oDYrM/eMZ6r9kDyxymE+YfpD3yRWaerbCuTAS9uuw=="
  pullSecretRef:
    name: assisted-deployment-pull-secret
  #ignitionConfigOverride: '{"ignition": {"version": "3.1.0"}, "storage": {"files": [{"path": "/etc/someconfig", "contents": {"source": "data:text/plain;base64,aGVscGltdHJhcHBlZGluYXN3YWdnZXJzcGVj"}}]}}'
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: tosin-ocp
