---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: tosin-ocp
  namespace: tosin-ocp
  labels:
    name: tosin-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: Datacenter
    cluster: Cluster
    cluster-name: tosin-ocp
    agentclusterinstalls.extensions.hive.openshift.io/location: loe-atl1
    networkType: static
spec:
  agentLabels:
    agentclusterinstalls.extensions.hive.openshift.io/location: loe-atl1
  clusterRef:
    name: tosin-ocp
    namespace: tosin-ocp
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCsrRp8qXVozZid40no9uZa44+oiK/+5asEiz4og4HXs6S2xcY8GbS2okCe+nujzaD4NyYBaE28aJKxVDJt/BlmIr9Cd82Az9xaIa1UQJLJZDrBMWTAROn/ixegETFQYv3Hsfo9SoJFqgzJb/yBy7LqJvRY7exZdUAoGRCeiInirmbw4710xrubDF1xI1kcXbuPu3ajEGgx5pW/b2gJDQ6rTO+6nt8JioMmNv+ULfpYMkifpwxy6jtuen0udoGRlw1DdcR7DzUGpSDpKNhrtB+oQ5VBaA5SKHwznfh0fsh3/R03tx3aKmdQxSW1owpSRdQ/reSicyBu9JwdHg1vymgenoPBOwR7T1lBqTOOe++M9Z+LnnlzT4kQqOgVniyw+lrPjrl0LoL7wI6fZAFCF8IkqTl8BLUdFe1ST2v6EGDL01CxsbUXBe+7KPbnd+VBb8w4YN/KuWxcjIxH9xUyzz8ogLkIdNrnhUs4v512FWuejNFeks+CZFp4zk3bQbtCc0ZOzBday7JJ3VjYv6hqYXq6bq3+V9ngFLJWw7QZ8so7jernc+eSzjePB717fRtlJzy5CAwMxl87JbonSBbwsqbq0Ab03X3/VhmIq963YKQGVhwVtrqLUZfaD0w87qeaqLq0rZi9QIAPIdr6r87MQ+8aH1z8q80OCNbbY5UF8zoeUw=="
  pullSecretRef:
    name: assisted-deployment-pull-secret
  #ignitionConfigOverride: '{"ignition": {"version": "3.1.0"}, "storage": {"files": [{"path": "/etc/someconfig", "contents": {"source": "data:text/plain;base64,aGVscGltdHJhcHBlZGluYXN3YWdnZXJzcGVj"}}]}}'
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: tosin-ocp
