---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: sno-ocp
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "ztp-credentials/assisted-deployment-pull-secret"
  labels:
    name: sno-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: LabDC
    cluster: LabCluster
    cluster-name: sno-ocp
data: