---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: sno-ocp
  namespace: sno-ocp
  labels:
    name: sno-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: LabDC
    cluster: LabCluster
    cluster-name: sno-ocp
spec:
  clusterDeploymentRef:
    name: sno-ocp
  imageSetRef:
    name: openshift-v4.9.9
  #apiVIP: "192.168.42.74"
  #ingressVIP: "192.168.42.74"
  holdInstallation: false
  networking:
    networkType: OVNKubernetes
    #userManagedNetworking: false
    clusterNetwork:
      - cidr: "10.128.0.0/14"
        hostPrefix: 23
    serviceNetwork:
      - "172.30.0.0/16"
    machineNetwork:
      - cidr: "192.168.42.0/24"
  provisionRequirements:
    controlPlaneAgents: 1
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCnVCo5q3BDWJXzV03pQjhXRsJFHoR89KanoiWcGka+vIQsS5NmUdmswVRPMM8HomAktcNiLhZoZ+ZQhyqqUWKwdLPgl5AEKCWmTh+ag89D4X1plizHhMh6RsBdKCpJnhzHPMWrtkz0hjS6H9pKcYBY9dgWlfrNNBkayh+o+X3+xBQwUc+dGPYSYLq2tdUENnS3VTZWuJjbIm/vaI3bqg+RhgQO+AyoQjZLc+8vhnjxyiMomdsIvo2cO6nItDhMFBG1jhjPh7kgiFdmt+G+3CaUsbN0+DxNz2ylyuHNqdYUkVNYSvG+bVYfC1woSDbeVUd6OZIwoltAjtwA/hVHybiDCCtkb8Pyge/XWzp26+2gma9Ey4S2NkwpvSTsjAn/GZrjXb5bq+al0ZyuAXlfqouJ5gwg75w9T6MY8mBfnEF+9MRmn4RroSzbRQRrcSnZgPTMKMs5jebGGeqY2iPoYHLV4IE0Bn7Bid/M+RvqEBDlCqXZ8uxngXtE+a7JVhOnkWomsXFlQ2hAuvNwpd/eIX58WmNQDs1vPDdvziQr3qCtP23gRyzErt7e32DXMXpqbrHtQJoWSuL9N1vI2UN8s5sSXvSRR+m2xFGleEWaaqnxvg39sXgnoBIicknv+UUZHctIYD7Xilyen6d0SU3vGm502zf9jReixMp/K8++kKJydw=="
