---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: sno-ocp
  namespace: sno-ocp
  labels:
    name: sno-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: LabDC
    cluster: LabCluster
    cluster-name: sno-ocp
    agentclusterinstalls.extensions.hive.openshift.io/location: loe-1
    networkType: static
spec:
  agentLabels:
    agentclusterinstalls.extensions.hive.openshift.io/location: loe-1
  clusterRef:
    name: sno-ocp
    namespace: sno-ocp
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzUpnWlI+HyPXHnvaW6uVd+5KghVgDtX4ZXVVGNug35+hhA7+7oo6zfhPgOH/3B60+7wUmOXXq0UNUEU9cg8ayptCL/Ovs7ekTXNO6HzkGkpdq2UTsrp1nmboy5rHgNuN0zPQivPPSPgJhf64XtF/QXIMGCoHzL4on3z+KBsN11JnIMLoLwj3j7V40MHDas3TX9bq+sxYXUmNLhunE+y4qVgsX0oNeIt8RuPESb+yAvjIlWAwUiO9QfbobdtOQ6uzP34W2vP2kbrP8n8Z28TDlIPOkHYSl2wpFCR7cbHrOcV/pt2VCH48AZy2HhPwdkn2QxpNUOT0/FlFErgg9h2ntFHL/UT3TsZfOZMxicDgp5/p8+rxXqy2gaS+4eZWXhxa9GsdM8Cf1YI66e/qd9MPQii/mt13JOJyCk9GXq7urlZQWglFh4sNIz59VjccuipnXS5aQiC6BqpAQJjxxLfObqkHbGTO6hHTHMK4uhXrczY9m19A2jNlQ8lYSOXYxkKm+4uFf6+ziBpL0OBGnRVlSgY2Pf//6AYTlk1d1/MYsauYuY6hDPnuiy2qEFR48b1d9KAerbibkqw50rOY5dg8Fow2OvzPgwemDlIUkw3+NpqOwPb2Rso4qwLfOo0q674xVOXsZoOA327lk2zM4m1aGSFOOX+ibMtaLQ9qnXatZGQ=="
  pullSecretRef:
    name: assisted-deployment-pull-secret
  #ignitionConfigOverride: '{"ignition": {"version": "3.1.0"}, "storage": {"files": [{"path": "/etc/someconfig", "contents": {"source": "data:text/plain;base64,aGVscGltdHJhcHBlZGluYXN3YWdnZXJzcGVj"}}]}}'
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: sno-ocp
