---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: loe-sno-atl1
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "ztp-credentials/assisted-deployment-pull-secret"
  labels:
    name: loe-sno-atl1
    cloud: vSphere
    vendor: OpenShift
    datacenter: Datacenter
    cluster: Cluster
    cluster-name: loe-sno-atl1
data: