---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: loe-sno-atl1-vsphere-bootstrap
  namespace: loe-sno-atl1
  labels:
    name: loe-sno-atl1
    cloud: vSphere
    vendor: OpenShift
    datacenter: Datacenter
    cluster: Cluster
    cluster-name: loe-sno-atl1
spec:
  tower_auth_secret: ansible-tower-credentials
  job_template_name: vsphere-infra-ztp
  extra_vars:
    vcenter_credentials_secret_namespace: loe-sno-atl1
    vcenter_credentials_secret_name: loe-atl1-vcenter-credentials

    infraenv_namespace: loe-sno-atl1
    infraenv_name: loe-sno-atl1

    cluster_configmap_namespace: loe-sno-atl1
    cluster_configmap_name: loe-sno-atl1-cluster-config
