---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: sno-ocp
  namespace: sno-ocp
  labels:
    name: sno-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: LabDC
    cluster: LabCluster
    cluster-name: sno-ocp
    agentclusterinstalls.extensions.hive.openshift.io/location: loe-rhu
    networkType: static
spec:
  agentLabels:
    agentclusterinstalls.extensions.hive.openshift.io/location: loe-rhu
  clusterRef:
    name: sno-ocp
    namespace: sno-ocp
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCx9ygSoAduS/FJeBoeeEfJcaovN4HN/wWZFimPsuqUo6W9cERywRj0tMqxpUZHgc85nx3cwnQ98osDoGkEr7/+Cl8aongTq9YLdPm4OVPa46B7LMq605gAfQS2fhjKB1GzfCPvgy5Tne15mFGbuPtGBOT3yIPSgbGaK5iTx5/2V0HFRDxUv6iAdO+0EVjQ52pNdRcb7XAe6ei8CC/YlV7ZDAH9Tnpy7WVPycqMdGJuHcGQNn5Iyv9dIF7GgMkNJcc6rkq8QWuNb+yUfNMpZzV42qbSMoIWWKhtgGhQfRoxty/muAVlzIjVwnahBWkRCrz/5D57e7Iee1uHO+QCLH9eRdYm4bUk8HJrsOL0rihz7f4wlxHDy4NyEgB4n3aL57kaopOWzUW0LibsX91x0ZircaA7CYT46k88BTmtwoPd0ilojiNAaMw68sJ4VvQmZpwNPhzJ8vTLKVUQA0J5AJxeRWencZiKNNQ+T7haXzLcxNynHrZEkgVcMXjpEmb5magVWb1JLZ5bp2nYumPY7hlUsubDppccKSjEUjlwQvjyFqmVoZ0s2PbmSgC+qLGN4swrjAywRwdHHcNeYZUZlb/quatcObeVcZsGrfwmDlfJokyIVr412mk5U0k9cqmGO0FLWST9l8gxlaZO1X3ZjHqA+QEztEDA3t9HAaHUYHtnDw=="
  pullSecretRef:
    name: assisted-deployment-pull-secret
  #ignitionConfigOverride: '{"ignition": {"version": "3.1.0"}, "storage": {"files": [{"path": "/etc/someconfig", "contents": {"source": "data:text/plain;base64,aGVscGltdHJhcHBlZGluYXN3YWdnZXJzcGVj"}}]}}'
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: sno-ocp
