---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: sno-ocp-cluster-config
  namespace: sno-ocp
  labels:
    name: sno-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: LabDC
    cluster: LabCluster
    cluster-name: sno-ocp
data:
  cluster_name: sno-ocp
  cluster_provider: vsphere
  cluster_type: sno

  vsphere_datacenter: LabDC
  vsphere_cluster: LabCluster
  vsphere_datastore: nvme
  vsphere_network: VMNetwork

  cluster_nodes: '[{"interfaces": [{"dhcp": false, "ipv4": [{"address": "192.168.42.71", "prefix": 24}], "mac_address": "00:51:56:42:06:09", "name": "ens192", "routes": [{"destination": "0.0.0.0/0", "next_hop_address": "192.168.42.1", "next_hop_interface": "ens192", "table_id": 254}]}], "name": "sno-white", "type": "sno-node", "vm": {"cpu_cores": 8, "cpu_sockets": 1, "cpu_threads": 1, "disks": [{"name": "boot", "size": 240}], "memory": 65536}}]'
