---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: sno-white-sno-ocp
  namespace: sno-ocp
  labels:
    name: sno-ocp
    cloud: vSphere
    vendor: OpenShift
    datacenter: LabDC
    cluster: LabCluster
    cluster-name: sno-ocp
    hostname: sno-white
spec:
  config:
    dns-resolver:
      config:
        server:
          - 192.168.42.9
          - 192.168.42.10
        search:
          - kemo.labs
          - kemo.network
    interfaces:
      - ipv4:
          address:
            - ip: 192.168.42.71
              prefix-length: 24
          dhcp: False
          enabled: true
        name: ens192
        state: up
        type: ethernet
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.42.1
          next-hop-interface: ens192
          table-id: 254
  interfaces:
    - name: ens192
      macAddress: 00:51:56:42:06:09
