---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: loe-sno-atl2-loe-sno-atl2
  namespace: loe-sno-atl2
  labels:
    name: loe-sno-atl2
    cloud: vSphere
    vendor: OpenShift
    datacenter: Datacenter
    cluster: Cluster
    cluster-name: loe-sno-atl2
    hostname: loe-sno-atl2
spec:
  config:
    dns-resolver:
      config:
        server:
          - 192.168.42.9
          - 192.168.42.10
        search:
          - atl.kemo.labs
    interfaces:
      - ipv4:
          address:
            - ip: 192.168.1.7
              prefix-length: 24
          dhcp: False
          enabled: true
        name: ens192
        state: up
        type: ethernet
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.1.1
          next-hop-interface: ens192
          table-id: 254
  interfaces:
    - name: ens192
      macAddress: 00:51:56:42:06:13
